= Change and Improvement

It is very difficult for us humans to notice our own flaws. We generally have
a compulsive need to justify our failures on external entities and our
negative traits as being irrelevant. However, we are good at finding
weaknesses in others. Perhaps this is the best defense.

Some examples of weaknesses are:

[options="compact"]
- procrastination, distraction
- smoking, substance abuse
- unhealthy eating, obesity
- anger
- unrealistic positivity
- wanting to be always be right
- closed-mindedness
- low accountability
- strategic detachment

People in one's professional and personal circles might have other motivations
(e.g. fearing displeasure or worse wanting to flatter) or may lack the skill
to spot areas of improvements. These are challenges to getting help from
others. Yet, seeking help from others, particularly someone who has been paid
(e.g. doctor) is a good idea.

Regardless of the availability of constructive criticism, lasting change
requires self-motivation. This depends on accepting that a causal association
exists between undesirable outcome and a particular behavior. Acceptance
becomes difficult when the impact of an action is not immediate. For instance,
smoking is dangerous and can even be regarded as comical when living in a city
that has severely poor air quality. Yet this behavior is fairly prevalent
particularly among youngsters.

Pain (e.g. fine for breaking traffic rules) appears to be an effective change
agent although we would like this to not be true. It would have been better if
we all voluntarily did the right thing. Pain is an indicator that we are not
headed in the right direction.

We all have about 8-12 working hours in a day. This is not much. Assuming a
life expectancy of 80 years and the fact that the initial 25 years of life are
spent as per the guidance of elders and institutions, we have less than 25
years to spend as per our best understanding.
