= DNF Command Cheat Sheet
Pradeep Roy
:source-highlighter: rouge
:source-language: console
:f22announcemagazine: https://fedoramagazine.org/fedora-22-released/

== Motivation

Dandified Yum, or DNF, became the default package manager in Fedora 22
({f22announcemagazine}[announce]). I have experience with Yum from working on
applications on CentOS 6 and 7. Now, in 2026, the RHEL-family systems I
encounter use DNF rather than Yum. The idea behind this document is to
collect useful DNF commands and make them easily accessible.

== Platform

The commands in this document were tested in a Rocky Linux 8 container.

== Terminology

In this document, the term "repository" means an enabled repository unless
stated otherwise. Disabled repositories don't participate unless explicit
command-line switches are used. This convention avoids repeatedly qualifying
"repository" with "enabled".

== Examples

=== Searching Packages

Perhaps the first thing one wants to do is search for a package without
knowing its exact name. The following example searches for package names and
summaries that contain both `postgresql` and `server`:

----
$ dnf search postgresql server
----

To find which package provides a particular file, use the `whatprovides`
command.

----
$ dnf whatprovides '*/yaml-0.1.pc'
----

=== Installing Packages

When the name of a package is known, use `dnf install` to install it.

The `-y` switch automatically answers yes to confirmation prompts, which is
useful in Dockerfiles and scripts.

----
$ sudo dnf install -y postgresql-server
----

Use `--enablerepo` when a package is available from a repository that is
configured on the system but disabled by default. This is common for
development packages in Rocky Linux 8's `powertools` repository.

----
$ sudo dnf --enablerepo=powertools install -y autoconf-archive
----

The EPEL repository contains many useful packages such as `hiredis-devel` or
`ShellCheck`. Make the repository available by installing `epel-release`:

----
$ sudo dnf install -y epel-release
----

Use `--disablerepo` when a configured repository is not relevant to the
current operation or is causing metadata, GPG verification or network
problems. The switch accepts globs, so `--disablerepo='epel*'` can disable
multiple matching repositories.

----
$ sudo dnf --disablerepo='epel*' install -y postgresql-server
----

=== Listing Repositories

The following command lists all enabled repositories:

----
$ dnf repolist
----

To list disabled repositories:

----
$ dnf repolist --disabled
----

Use the following command to see every configured repository. This is useful
before deciding whether `--enablerepo` is needed.

----
$ dnf repolist --all
----

=== Listing Packages

Use `dnf list` variants when you want to check whether specific packages are
installed or available from enabled repositories. To list all installed
packages:

----
$ dnf list --installed
----

NOTE: Merely running `dnf list` is likely to produce a long list of all
packages available from repositories and all packages installed on the system.

Add `--enablerepo` when the package may be available from a disabled
repository.

----
$ dnf --enablerepo=powertools list autoconf-archive doxygen
----

Quoted wildcards can be used to limit results to matching package names:

----
$ dnf --enablerepo=powertools list '*dpdk*' '*hiredis*' '*luajit*'
----

=== Changing Configuration

Make the `config-manager` command available by installing `dnf-plugins-core`:

----
$ sudo dnf install -y dnf-plugins-core
----

Permanently enable the `powertools` repository:

----
$ sudo dnf config-manager --set-enabled powertools
----

=== Refreshing Repository Metadata

After adding or changing repository files, use `dnf makecache` to fetch
metadata and identify repository problems before attempting package
installation.

----
$ sudo dnf makecache
----

== Further Reading

- https://fedoraproject.org/wiki/F22_release_announcement[Fedora 22 Release
  Announcement]
- https://dnf.readthedocs.io/en/latest/command_ref.html[DNF Command Reference]
- https://dnf.readthedocs.io/en/latest/conf_ref.html[DNF Configuration
  Reference]
