= Stages of Ego

Over the weekend I had a conversation with a friend from college. We reflected
upon the interaction between experience and aging and recognized that our
sense of self probably goes through these stages:

- *Player* Young and not aware of aging. This could be said to be the
  condition till the age of 25. Survival and standing on one's own feet is of
  highest importance. At this stage, people are generally willing to change
  and listen to advice.
- *Achiever* The combination of youth, hard-work, luck and skill brings about
  significant success. This could be reaching financial or social milestones
  or even getting a big dream fulfilled. One can remain an achiever if he keeps
  growing at a steady pace. For most people things start to decline after
  15 years as an achiever.
- *Sage* Criticizes youngsters for their laziness and impatience. Output has
  diminished due to aging. But the sage compensates with his wisdom. There is
  a strong tendency to organize daily life as per one's own preferences. High
  resistance to change. Often jumps to conclusions when listening but can
  speak endlessly on own topics of interest. Mentions about his achievements
  in the past and preaches how people are pursuing incorrect goals and will
  get the correct world-view later. This stage can continue till ripe old age.
- *Spectator* Stops criticizing and focuses on personal well-being. Knows that
  one is not special and has to eventually give way, whether voluntarily or
  through compulsion. This stage can start in middle age and can be a period
  of positive impact on society.
