= Personal Tips & Tricks
Pradeep Roy
:source-highlighter: rouge
:source-language: console

My working environment is mostly Ubuntu 22.04 or Oracle Linux 9. Earlier, it
used to be CentOS 7.

== OpenSSH - Generating Keys

Generating authentication keys for OpenSSH:

----
$ ssh-keygen -t rsa -b 4096 -C <hostname>
----

== OpenSSH - Client Configuration

Connecting to hosts via `ssh` is a common activity for me. Leveraging the
client configuration file (`~/.ssh/config`) is a productivity improving
tip. This file makes it possible to separately specify port number, user name,
identity file for hosts. I generally find it useful when connecting to servers
that are listening on non-standard ports. Example:

[,ssh]
----
Host my-sftp-2022
User sftpuser
Hostname 192.168.1.5
IdentityFile ~/.ssh/my-key.pem
Port 2022
----

Such a configuration generally shortens the command-line and can even be
necessary when using `lftp` to connect to hosts that support public key
authentication only (not password).

== APT - Proxy

To make APT use a HTTP/HTTPS proxy create a file named `95proxy` inside the
`/etc/apt/apt.conf.d/` directory. The number 95 ensures that the config file
is read late possibly not getting over-ridden by a setting that might have got
loaded later.

----
> cat /etc/apt/apt.conf.d/95proxy
Acquire::http::Proxy "http://172.18.40.8:8888/";
Acquire::https::Proxy "http://172.18.40.8:8888/";
----

These options are defined in the `apt-transport-http(1)` man page.

== Tmux - Status Line

These commands worked for me on Tmux 3.2a. The status line printed by Tmux at
the bottom is controlled by the `status-right` option.  One can view the
current value by running:

----
$ tmux show-option -g status-right
----

To temporarily set the status:

----
$ tmux set -g status-right "%H:%M | %d-%b-%y"
----

With colours:

----
$ tmux set-option -g status-right "#[fg=green]%H:%M #[fg=black]| #[fg=blue,bold]%d-%b-%y"
----

== Sysstat - pidstat timestamp

This issue occurred on 7.9.2009 with sysstat 10.1.5-20.el7_9. `pidstat`
printed the opening timestamp in a different format depending on the logged-in
user:

Sample 1 (memory value is at position 8):

[,text]
----
05:29:05 AM     0      7144 224393.65      0.00 4629044 1943848   1.97  app
----

Sample 2 (memory value is at position 7):

[,text]
----
04:14:22        0     34658 210790.37      0.00 4786596 2050684   2.08  app
----

We were not able to resolve by using the `S_TIME_FORMAT` environment variable.
We resolved it by using the `-h` switch that made `pidstat` print the
timestamp in seconds since Epoch.

== AsciiDoc - PDF

Converting Asciidoc files info PDF makes it possible to share content with
anyone.

=== Debian 12

I have used Asciidoctor PDF 2.3.4 on Debian 12.7. It generates nicely
formatted documents with no additional command-line switches.

----
$ sudo apt-get install ruby-asciidoctor-pdf
----

The Rouge
https://docs.asciidoctor.org/pdf-converter/latest/syntax-highlighting/[syntax
highlighter] is nicely integrated with Asciidoctor PDF. It is not essential
for PDF conversion but using it adds colour to source blocks.

----
$ sudo apt-get install ruby-rouge
----

One can start using it by merely adding the following line in the document
header:

[,text]
----
:source-highlighter: rouge
----

To print the list of languages supported by Rogue:

----
$ rougify list
----

Convert AsciiDoc to PDF:

----
$ asciidoctor-pdf <file.adoc>
----

=== CentOS 7

Install the packages necessary to convert AsciiDoc (usually `.adoc` file
extension) file to PDF:

----
$ sudo yum install asciidoc dblatex
----

A command-line that I have used:

----
$ a2x --icons-dir /usr/share/asciidoc/images -f pdf  --dblatex-opts "-P doc.publisher.show=0 -P latex.output.revhistory=0 -Pdoc.layout=\"coverpage frontmatter mainmatter index \"" --doctype=article README.adoc
----

This is useful when the table of contents needs to be disabled. Otherwise, the
`-Pdoc.layout` switch is not required.

== AsciiDoc - Relative Links

To generate hyperlinks to a file inside a Git repo use the `link` macro
(https://docs.asciidoctor.org/asciidoc/latest/macros/link-macro/[source]).
Example:

[,text]
----
link:path/to/file.pdf[file.pdf]
----

== Markdown - Generate Table of Contents

https://github.com/thlorenz/doctoc[Doctoc] can be used to generate table of
contents in markdown files. Essentially:

----
$ sudo npm install -g doctoc
----

The table of contents of this file has been generated using `doctoc`:

----
$ doctoc Tips.md
----

== Markdown - CLI Preview

https://github.com/charmbracelet/glow[Glow] makes it possible to preview
Markdown files on the terminal. Download an install a suitable binary package
from the https://github.com/charmbracelet/glow/releases[releases page]

== Markdown - Table Genrator

The https://www.tablesgenerator.com/markdown_tables[tables generator]
site can be used to generate markdown for tables.

== Vim - Installing Vim 8 on CentOS 7

It is always easiest to install from binary packages (than compiling from
source). Vim 8 is available from the GhettoForge Plus repo. Install it:

----
$ sudo yum install https://mirror.ghettoforge.org/distributions/gf/gf-release-latest.gf.el7.noarch.rpm
----

The repo has to be manually enabled:

----
$ sudo vi /etc/yum.repos.d/gf.repo
----

The package conflicts with the one coming from base CentOS and so has to be
removed. Do keep a backup of `sudo` config (e.g. `/etc/sudoers`) because it
gets removed in the process:

----
$ sudo yum autoremove vim-minimal
$ sudo yum install vim-enhanced sudo
----

== Vim - Building Vim 8 on CentOS 7

The main reason why I wanted to upgrade to Vim 8 on CentOS 7 was the
https://github.com/fatih/vim-go[vim-go] plugin. It did not find the version
that came from GhettoForge new enough and kept complaining. Therefore, I had to
resort to compiling from sources:

----
$ sudo yum groupinstall "Development Tools"
$ sudo yum install ncurses ncurses-devel
----

As of this writing the tip of the master branch was `4b4b1b8` tagged as
`v8.2.3426`.

----
$ git clone https://github.com/vim/vim.git
$ cd vim
$ ./configure --with-features=huge --enable-multibyte --enable-rubyinterp --enable-pythoninterp --enable-luainterp --prefix=/usr/local/vim8
----

Enabling Perl did not work for me. The compilation failed with an "Unrecognized
switch: -rototypes" error message. So, I had to drop it.

----
$ sudo mkdir /usr/local/vim8
$ sudo chown osboxes:osboxes /usr/local/vim8
----

Finally, compile and install:

----
$ make
$ make install
----

Notice how the install step was run as non-root. This ensures that we don't
modify system-wide locations any more than expected. If uninstallation is
required, then removing this one directory is enough.

----
$ sudo yum autoremove vim-enhanced
$ sudo ln -s /usr/local/vim8/bin/vim /usr/local/bin/
----

== Go - Setting up Vim

After installing Vim 8, just do:

----
$ git clone https://github.com/fatih/vim-go.git ~/.vim/pack/plugins/start/vim-go
----

Commits that have worked in the past:

- **2024-01-14** Go 1.18.10 (https://github.com/fatih/vim-go/commit/e2e7ad7c[commit])
- **2023-06-21** Go 1.18.10 (https://github.com/fatih/vim-go/commit/397a9c57[commit])
- **2023-05-29** Go 1.18.10 (https://github.com/fatih/vim-go/commit/2a874910[commit])

That's it! For details see https://tpaschalis.github.io/vim-go-setup/[this] blog.

== Go - Directory Layout

I have kind of started liking the Go Project
https://github.com/golang-standards/project-layout[layout].

== Go - Linters

https://golangci-lint.run/[Golangci-lint] is a front-end to dozens of Go
linters. The use of linters helps in avoiding coding pitfalls. It can be
installed by running:

----
$ curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b <dir>
----

Where `<dir>` is the directory into which the executable will be downloaded.
Example:

----
$ curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b ~/.local/bin/
----

== Go - Private Repository

Using a private repository in a Go involves the execution of multiple steps.
ONE, tell Git to use alternative SSH protocol to make `go get` commands work:

----
$ git config --global url."git@gitlab.mycompany.com:".insteadOf "https://gitlab.mycompany.com/"
----

TWO, tell Go do disable validating certain modules:

----
$ go env -w GOPRIVATE=gitlab.mycompany.com
----

Do, `go help private` for more information.

THREE, ensure that the package's module uses the `.git` extension in its `go.mod`:

[,text]
----
module gitlab.mycompany.com/group/subgroup/playground.git
----

FOUR, include the `.git` extension in the `import` declaration. Example:

== Git - Git 2 on CentOS 7

Installing the newer Git 2 on CentOS 7 is required to avoid `git fetch-pack`
errors (https://github.com/golang/go/issues/38373[38373]). First, uninstall
Git coming from base CentOS:

----
$ sudo yum erase git perl-Git
----

Then, install the Inline with Upstream Stable (https://ius.io/[IUS]) Yum
repository:

----
$ yum install https://repo.ius.io/ius-release-el7.rpm https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
----

Install Git 2:

----
$ sudo yum install git222
----

== Git - Email id per Repo

Sometimes there is a need to use separate author emails IDs in Git commits
residing in differente repos (e.g.  work and personal). To setup an email ID
specific to a repo, change directory to it and then run:

----
$ git config user.email "own_email@domain"
----

== Git - Renaming branches

----
$ git branch -m main master
$ git push -u origin master
$ git push origin --delete main
----

== Python - Pip on Python 2.7

To install a newer version of Pip on CentOS 7 than the one coming with the
distribution, do:

----
$ curl -O https://bootstrap.pypa.io/pip/2.7/get-pip.py
$ python get-pip.py
----

This helped me get Pip 20.3.4.

== Python - requirements.txt

Dependencies of a Python codebase are often specified in a `requirements.txt`
file. An automated way to create this file is through the use of
https://github.com/bndr/pipreqs[pipreqs] that can be installed on Ubuntu 22.04
by running the following commands:

----
$ sudo apt install python3-pip
$ sudo pip3 install pipreqs
----

Oracle Linux 9 users can do:

----
$ sudo yum install python3-pip
$ sudo pip3 install pipreqs
----

Example usage:

----
$ cd path/to/project
$ pipreqs .
----

Some readers might have noticed that I wrote `pip3` instead of `pip`. In
environments that have either Python 3 or Python 2 installed but not both, the
command `pip` is likely to refer to the correct Python installation. However,
this might not work in mixed systems that have both versions installed.
Therefore, it is appropriate to specifically write `pip3` when working with
Python 3 packages and likewise for `pip` and Python 2.

== C/C++ - Reformat

https://astyle.sourceforge.net/astyle.html[Astyle] can be used to ensure
consistent code indentation and formatting. The following works on Ubuntu
22.04:

----
$ sudo apt-get install astyle
----

Example command-line

----
$ LC_ALL="en_US.UTF-8" astyle -q -R --style=java -H '*.java' '*.c' '*.cc' '*.cpp' '*.h'
----

== C/C++ - Core Dumps

Enabling core dumps depends on kernel (Linux) settings. Configuration
that worked for me on Oracle Linux 9:

----
$ echo "/var/dumps/core.%e.%p" | sudo tee /proc/sys/kernel/core_pattern
----

The directory mentioned in `core_pattern`
(https://www.kernel.org/doc/Documentation/sysctl/kernel.txt[doc]) must exist.

----
$ sudo mkdir /var/dumps
----

Besides, the shell's resource limit for core files might have to be changed:

----
$ ulimit -c unlimited
----

== C/C++ - Detecting Memory Errors

AddressSanitizer was added to GCC in the
https://gcc.gnu.org/gcc-4.8/changes.html[4.8] release. To use on Oracle Linux
9, an additional package has to be installed apart from `gcc`.

----
$ sudo yum install libasan.x86_64
----

Example program with a memory leak
(https://stackoverflow.com/questions/47201087/gcc-how-to-use-address-sanitizer[source]):

[,c]
----
int main()
{
  int *prt = new int;
  return 0;
}
----

Let us say it is saved in a file named `main.cc`. To compile with the address
sanitizer enabled, do:

----
$ g++ -g -O0 -fsanitize=address main.cc
----

Running the generated executable would report the error along with the source
line number.

== Shell - Linter

Linters catch common coding mistake. I have found that a report mentioning
specific issues provides motivation to remove them. This is more powerful than
a bunch of guidelines that have to be kept in one's head. A useful shell
script linter is `shellcheck`. Install it on Ubuntu 22.04 by running

----
$ sudo apt-get install shellcheck
----

Use the following command to run a shell script through the linter:

----
$ shellcheck -x <script>
----

== Shell - lftp

`lftp` is a useful command. The interaction with a FTP server is faster and
more Bash-like. It also has an option to download complete directory trees.
Install it by running:

----
$ sudo yum install lftp
----

The command reads login information from `/.netrc`. Example contents:

[,text]
----
machine <hostname1> login <user1> password <pass1>
machine <hostname2>.login <user2> password <pass2>
----

Then logging to a server and directly switching to a directory
becomes very convenient:

----
$ lftp sftp://<user1>@<hostname1>/upload
----

== Shell - find

Sometimes I want to search for files that have been recently downloaded or
edited. This means finding files on the basis of last modification time. The
following command finds files modified within the last 100 days:

----
$ find . -type f -mtime -100
----

== CMake - Python

This tip is useful at the time of packaging a Python module. The directory
where modules should be copied differs between Linux distributions. It could
be `/usr/lib/python3/dist-packages` on Ubuntu and
`/usr/lib64/python3.9/site-packages` on a Fedora derived
distribution. CMake can auto-detect the value and make it available through a
variable. This can be done by:

[,cmake]
----
find_package(Python3 REQUIRED COMPONENTS Interpreter Development)
----

Subsequently, the `Python3_SITEARCH` variable will containe the directory
path.

== CMake - Java

I want to give two tips through this item. First is that the variables that
will get defined through a successful `find_package()` call can be known by
reading a `Find<PackageName>.cmake` file. These files are located inside
`/usr/share/cmake-*/Modules`. An actual example from Ubuntu 22.04 is
`/usr/share/cmake-3.22/Modules/FindJNI.cmake`. Second is that a successful
call depends on the `JAVA_HOME` environment variable being defined. Example:

----
$ echo $JAVA_HOME
/usr/lib/jvm/java-21-openjdk-amd64
----

For details around `find_package()` refer `cmake-commands` man page.

== Names - System Facts

A source of system related variable names that can be used in shell scripts is
in the CMake man page, `/etc/os-release`. Here is a list that I have
constructed after studying such sources:

- OS_NAME="Ubuntu"
- OS_NAME_PRETTY="Ubuntu 22.04.4 LTS"
- OS_VERSION_ID="22.04.4" I don't want anything around release because it
  causes confusion with version.
- OS_VERSION_CODENAME="jammy"
- OS_ID="ubuntu"
- OS_ID_LIKE="debian"

== Locale

Few of my text files don't get correctly rendered unless the
https://wiki.archlinux.org/title/Locale[locale] is set to
en_US.UTF-8. To display the currently set locale use the `locale` command. If
it is not set to en_US-UTF-8, then installing it on Oracle Linux 9 involves:

----
$ sudo yum install glibc-langpack-en.x86_64
$ sudo localectl set-locale LANG=en_US.UTF-8
----

== Maven - Downloading JAR

Maven has a cool feature to download a dependency (JAR) into the local
repository. Given the following XML config:

[,xml]
----
<groupId>com.github.siom79.japicmp</groupId>
<artifactId>japicmp</artifactId>
<version>0.23.1</version>
----

One can download the `japicmp` JAR by running:

----
$ mvn dependency:get -DgroupId=com.github.siom79.japicmp -DartifactId=japicmp -Dversion=0.23.1
----

== Trivy - Scanning JARs

Trivy is a useful open source vulnerability scanner. It can be easily
installed by following
https://trivy.dev/latest/getting-started/installation/[official instructions].
To install on a RHEL type of distribution (e.g. Oracle Linux 9), configure the
package manager:

[,text]
----
cat << EOF | sudo tee -a /etc/yum.repos.d/trivy.repo
[trivy]
name=Trivy repository
baseurl=https://aquasecurity.github.io/trivy-repo/rpm/releases/\$basearch/
gpgcheck=1
enabled=1
gpgkey=https://aquasecurity.github.io/trivy-repo/rpm/public.key
EOF
----

Followed by:

----
$ sudo yum update
$ sudo yum install trivy
----

To install on Ubuntu 22.04, configure APT:

----
$ sudo apt-get install gnupg2
$ curl -s https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg
$ echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
----

Followed by:

----
$ sudo apt-get update
$ sudo apt-get install trivy
----

To scan a single JAR:

----
$ trivy rootfs <path/to/jar>
----

To scan a Docker images selecting high and critical vulnerabilities only:

----
$ trivy image --severity HIGH,CRITICAL <name:tag>
----

== Curl - IP Geolocation

To get geo-location information of one's public IP address from the
command-line use:

----
$ curl https://ipinfo.io
{
  "ip": "117.199.196.56",
  "city": "Kolkata",
  "region": "West Bengal",
  "country": "IN",
  "loc": "22.5626,88.3630",
  "org": "AS9829 National Internet Backbone",
  "postal": "700001",
  "timezone": "Asia/Kolkata",
  "readme": "https://ipinfo.io/missingauth"
}
----

== Yum - Prevent Removal of Dependencies

Let us say there is a RPM package that we have created and it has sevaral
dependencies (hundreds of MBs) and no other package on the system needs those
dependencies. In such a situation, every time the package is erased by Yum,
all the dependencies get removed too. However, during rapid cycles of
development and testing removal and installation might have to be done several
times. It saves time if the dependencies are not removed. To do this with Yum,
make use of the `--noautoremove` command-line switch.

----
$ sudo yum erase --noautoremove <rpm>
----

== Packages - Available Version

Sometimes I want to know the available version of a package prior to
installing it. For instance, if the most recent Java 21 update happens
to be 21.0.6 (https://www.java.com/releases/[releases]) then I want to know if
this version can be installed on my system through the default package
manager. To check for available package version on Ubuntu 22.04 one can do:

----
$ apt-cache madison openjdk-21-jdk
----

An alternative command that also reports if the package is installed is:

----
$ apt-cache policy openjdk-21-jdk
----

To do the same thing on a RHEL-like system (e.g. Oracle Linux 9), do:

----
$ yum list java-21-openjdk.x86_64
----

Yum's `list` command needs a full package name. For instance, the argument
`man` does not list anything while `man-db` does so.

== MuPDF - Repairing PDF Files

This incident happend on Debian 12.7. I was able to open a PDF file in
Firefox 115.15.0 ESR but Evince 43.1 reported that the document was damaged
and could not open it.

Issues were reported by https://qpdf.readthedocs.io/en/stable/overview.html[qpdf]
as well:

----
$ qpdf --check receipt.pdf
WARNING: receipt.pdf: file is damaged
WARNING: receipt.pdf: can't find startxref
WARNING: receipt.pdf: Attempting to reconstruct cross-reference table
qpdf: receipt.pdf: unable to find trailer dictionary while recovering damaged file
----

The following command made it possible to create a repaired file:

----
$ mutool clean -gg receipt.pdf repaired.pdf
----

The https://mupdf.readthedocs.io/en/latest/tools/index.html[mutool] utility
can be installed by running:

----
$ sudo apt-get install mupdf-tools
----

== KrutiDev010 - PDF

I downloaded a PDF file from the web-site of a financial entity and wanted
to share it with someone. But for sake of safety I did not want to include
identification numbers.  This meant editing the PDF document.

LibreOffice 7.4.7.2 on Debian 12.7 was unable to render Hindi fonts correctly
that were used in the document. But the document could be viewed cleanly on
Evince 43.1. The solution was to extract the font data from the PDF file and
rebuild the system's font cache.

Listing the fonts in a PDF file can be done using the `pdffonts` command that
is made available on Debian 12.7 by running:

----
$ sudo apt-get install poppler-utils
----

The `pdffonts <file>` command printed:

----
name                         type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
Helvetica                    Type 1            WinAnsi          no  no  no       3  0
NXQTTJ+KrutiDev010           CID TrueType      Identity-H       yes yes yes      5  0
XGITZB+Calibri               CID TrueType      Identity-H       yes yes yes      6  0
Times-Roman                  Type 1            WinAnsi          no  no  no      14  0
----

The important line as the one containing `NXQTTJ+KrutiDev010`. It has to be
used when generating the font file using fontforge:

----
$ sudo apt install fontforge
$ fontforge <file>
----

A necessary step for LibreOffice to work is setting the "Fontname" field to
"KrutiDev010" after navigating from Element -> Font Info. Copy the generated
file to the fonts directory and rebuild the cache:

----
$ mkdir -p ~/.local/share/fonts
$ cp KrutiDev010.ttf ~/.local/share/fonts
$ ft-cache -f -v
----

Verification step:

----
$ fc-list | grep Kruti
/home/user/.local/share/fonts/KrutiDev010.ttf: KrutiDev010:style=Regular
----

Notice the second column of `KrutiDev010:style=Regular` in the output.

== WhatsApp - Android

Android 10 introduced scoped storage
(https://www.youtube.com/watch?v=UnJ3amzJM94[video]) that changed WhatsApp
media directory from `/storage/emulated/0/WhatsApp` to
`/storage/emulated/0/Android/media/com.whatsapp/WhatsApp`.

"To give users more control over their files and to limit file clutter, apps
that target Android 10 (API level 29) and higher are given scoped access into
external storage, or scoped storage, by default. Such apps have access only to
the app-specific directory on external storage, as well as specific types of
media that the app has created."
(https://developer.android.com/training/data-storage#scoped-storage[source])
